import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import { testAction } from "../store/actions/testAction";
import { Link } from "@material-ui/core";

export default function Home() {
  const dispatch = useDispatch();

  const handleClick = () => {
    dispatch(testAction("next-redux implementation"));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="http://localhost:3000/reduxtest">
          tester redux
        </Link>
      </main>
    </div>
  );
}
